image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

build_job:
  stage: build
  tags:
    - shell
  script:
    - echo "Maven compile started"
    - $MAVEN_HOME/bin/mvn compile
  artifacts:
    paths:
      - target/*.jar

test_job:
  stage: test
  tags:
    - shell
  script:
    - echo "Maven test started"
    - "mvn test"

package_job:
  stage: package
  tags:
    - shell
  script:
    - echo "Maven packaging started"
    - echo "mvn package"

deploy_job:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Maven deploy started"